name: accloudtant
channels:
- anne
- conda-forge
- natx
dependencies:
- boto3=1.1.4=py34_0
- botocore=1.2.10=py34_0
- click=4.1=py34_0
- clyent=1.2.0=py34_0
- dateutil=2.4.1=py34_0
- docutils=0.12=py34_0
- flake8=2.3.0=py34_0
- jmespath=0.9.0=py34_0
- mccabe=0.3=py34_1
- openssl=1.0.2f=0
- pep8=1.6.2=py34_0
- pip=8.0.1=py34_0
- py=1.4.31=py34_0
- pyflakes=0.9.2=py34_0
- pytest=2.8.5=py34_0
- pytest-benchmark=3.0.0=py34_0
- python=3.4.4=0
- python-dateutil=2.4.2=py34_0
- pytz=2015.7=py34_0
- pyyaml=3.11=py34_1
- readline=6.2=2
- requests=2.8.1=py34_0
- setuptools=19.4=py34_0
- six=1.10.0=py34_0
- sqlite=3.9.2=0
- tabulate=0.7.5=py34_0
- tk=8.5.18=0
- wheel=0.26.0=py34_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0
